import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cardData } from "./data";
import SearchBar from "./components/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let data = cardData;
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="con">
            <h1>
              <Link href={"/"}>
                <img src="/logo.svg" alt="logo" />
              </Link>
            </h1>
            <nav>
              <ul>
                {data.map((_, i) => {
                  return (
                    <li key={i}>
                      <Link href={data[i].url}>{data[i].title}</Link>
                    </li>
                  );
                })}
              </ul>
            </nav>
            <SearchBar />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
